version: '0.1'

services:
  db:
    container_name: taker_db
    image: postgres:15.1
    environment:
      POSTGRES_USER: alhasida
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/pgdata
    volumes:
      - db:/data/pgdata
    ports:
      - "5332:5432"
    networks:
      - db
    restart: unless-stopped
  alhasid-api:
    container_name: alhasid-api
    image: alialiev/frompast
#    можно так подключаться к бд, а можно через command, что закомментирован ниже
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/taker
    ports:
      - "8088:8080"
    networks:
      - db
    depends_on:
      - db
    restart: unless-stopped
#    command:
#      - --spring.datasource.url=jdbc:postgresql://db:5432/taker

networks:
  db:
    driver: bridge

volumes:
  db: