version: '0.1'

services:
  db:
    container_name: taker_db
    image: postgres:15.3
    environment:
      POSTGRES_USER: alhasida
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/pgdata
    volumes:
      - db:/data/pgdata
    ports:
      - "5332:5432"
    networks:
      - db
    restart: unless-stopped
  alhasid-api:
    container_name: alhasid-api
    image: alialiev/frompast
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/taker
    ports:
      - "8088:8080"
    networks:
      - db
    depends_on:
      - db
    restart: unless-stopped
  frontend-react:
    container_name: frontend-react
    image: alialiev/frompast-react
    build:
      context: frontend/react_frompast
      args:
        api_base_url: http://localhost:8088
    ports:
      - "3000:5173"
    depends_on:
      - alhasid-api
    restart: unless-stopped

networks:
  db:
    driver: bridge

volumes:
  db: